Creation endpoint create user
1701722767/proyecto pull request #7
Opened 2021-12-13 16:42 UTC by santiago-ocampo8

2021-12-13 16:45 UTC, AndresFelipe11 approved these changes

2021-12-13 21:21 UTC, 1701722767 requested changes

2021-12-13 21:21 UTC, 1701722767 commented on api/app/Http/Controllers/UserController.php
> +        $this->userModel->save();
move this before that notify

2021-12-14 01:09 UTC, 1701722767 approved these changes

2021-12-14 01:09 UTC, merged